
export type Language = 'en' | 'tr' | 'hi';

export type View = 
  | 'dashboard' 
  | 'procurement-orders' 
  | 'procurement-prices' 
  | 'procurement-escalation' 
  | 'procurement-suppliers' 
  | 'procurement-bom' 
  | 'logistics-reservation'
  | 'logistics-transport'
  | 'warehouse-dashboard' 
  | 'warehouse-inefficiency'
  | 'customs-dashboard'
  | 'customs-import'
  | 'customs-export';

export interface Translations {
  title: string;
  dashboard: string;
  procurement: string;
  logistics: string;
  warehouse: string;
  customs: string;
  aiInsights: string;
  totalBudget: string;
  actualSpend: string;
  unitPrice: string;
  quantity: string;
  efficiency: string;
  activeShipments: string;
  stockLevel: string;
  clearedItems: string;
  analyze: string;
  generating: string;
  salesTarget: string;
  variance: string;
  orderAnalysis: string;
  priceAnalysis: string;
  supplierPerformance: string;
  bomControl: string;
  budgetQty: string;
  actualQty: string;
  budgetPrice: string;
  actualPrice: string;
  budgetTotal: string;
  actualTotal: string;
  bomStatus: string;
  purchaseReq: string;
  purchaseOrder: string;
  customerOrder: string;
  status: string;
  mrpResult: string;
  component: string;
  errorCode: string;
  errorDetail: string;
  impactedReq: string;
  impactedPO: string;
  correctiveAction: string;
  escalationAnalysis: string;
  rawMaterial: string;
  labor: string;
  energy: string;
  other: string;
  currentPrice: string;
  newPrice: string;
  difference: string;
  budgetImpact: string;
  actualImpact: string;
  costBreakdown: string;
  targetPrice: string;
  overTargetPrice: string;
  overTargetImpact: string;
  overTargetQty: string;
  overBudgetPurchaseQty: string;
  overBudgetAvgPrice: string;
  overBudgetImpact: string;
  exchangeRateEffect: string;
  inflationEffect: string;
  macroDrivers: string;
  fxRate: string;
  inflationRate: string;
  reservationPerformance: string;
  salesRep: string;
  customer: string;
  product: string;
  waitTimeDays: string;
  stockCostImpact: string;
  financialImpact: string;
  opportunityLoss: string;
  totalImpact: string;
  thresholdWarning: string;
  stockCount: string;
  overtime: string;
  inefficiencyCosts: string;
  unnecessaryMovements: string;
  pickingCancellations: string;
  productWaitTime: string;
  movementList: string;
  inventoryTurnover: string;
  emptyShelfRate: string;
  costEffect: string;
  warehousePerformance: string;
  transportation: string;
  importShipments: string;
  exportShipments: string;
  localShipments: string;
  vehicleUtilization: string;
  shipmentPlan: string;
  loadFactor: string;
  destination: string;
  origin: string;
  eta: string;
  vesselVehicle: string;
  customsManagement: string;
  importDetails: string;
  exportDetails: string;
  declarationNo: string;
  hsCode: string;
  dutiesPaid: string;
  vesselName: string;
  clearanceTime: string;
  customsMap: string;
  // Dashboard specific translations
  vsLastMonth: string;
  delayRisk: string;
  nearingCapacity: string;
  optimalPerformance: string;
  budgetSync: string;
  budgetUtilization: string;
  utilized: string;
  unitPriceVariance: string;
  currentPrice: string;
  target: string;
  fleetDistribution: string;
  vehicleLoadEfficiency: string;
  fullLoad: string;
  partialLoad: string;
  underUtilized: string;
  onTimeArrivalRate: string;
  globalOtdRating: string;
  inventoryLabor: string;
  stockMovements: string;
  velocityTarget: string;
  complianceDuties: string;
  clearanceThroughput: string;
  fastLane: string;
  dutySavingsTracker: string;
  totalRecovery: string;
  targetReached: string;
  annualGoal: string;
  crossDepartmentalAudit: string;
  // Warehouse specific translations
  occupancy: string;
  inProgress: string;
  cycleCountingBatch: string;
  lastSevenDaysTotal: string;
  // Procurement specific translations
  components: string;
  packaging: string;
  mro: string;
  coldRolledSteel: string;
  aiComparison: string;
  aiType: string;
  generativeAI: string;
  discriminativeAI: string;
  goal: string;
  useCase: string;
  copilotAnalysis: string;
  limitationsTitle: string;
  canDo: string;
  cannotDo: string;
  performAnalysis: string;
  fetchingData: string;
  orderSummaryYear: string;
  openOrders: string;
  delayed: string;
  budgetQtyDiff: string;
  budgetPriceDiff: string;
  warehouseDeliveryDate: string;
  palletCount: string;
  totalBudgetImpact: string;
  originCountry: string;
  roiAnalysis: string;
  annualSavings: string;
  implementationCost: string;
  paybackPeriod: string;
}
